[theme]
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f1f3f4"
textColor = "#202124"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false
